name: .NET Core

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

defaults:
  run:
    working-directory: Urmel

jobs:
  build:

    strategy:
      matrix:
        os: [ ubuntu-latest ]
        project: [ BCEngineTests, UrmelTests ]
        
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.301
    - name: Install dependencies
      run: dotnet restore ${{ matrix.project }}
    - name: Build
      run: dotnet build --configuration Release --no-restore ${{ matrix.project }}
    - name: Test & publish code coverage
      uses: paambaati/codeclimate-action@v2.6.0
      env:
        CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}
      with:
        coverageCommand: dotnet test --no-restore --verbosity normal --collect:"XPlat Code Coverage" ${{ matrix.project }}
